In [1]:
import pandas as pd

In [2]:
pd.read_csv("surveys.csv")

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN
5,6,7,16,1977,1,PF,M,14.0,NaN
6,7,7,16,1977,2,PE,F,NaN,NaN
7,8,7,16,1977,1,DM,M,37.0,NaN
8,9,7,16,1977,1,DM,F,34.0,NaN
9,10,7,16,1977,6,PF,F,20.0,NaN
10,11,7,16,1977,5,DS,F,53.0,NaN
11,12,7,16,1977,7,DM,M,38.0,NaN
12,13,7,16,1977,3,DM,M,35.0,NaN
13,14,7,16,1977,8,DM,NaN,NaN,NaN
14,15,7,16,1977,6,DM,F,36.0,NaN
15,16,7,16,1977,4,DM,F,36.0,NaN
16,17,7,16,1977,3,DS,F,48.0,NaN
17,18,7,16,1977,2,PP,M,22.0,NaN
18,19,7,16,1977,4,PF,NaN,NaN,NaN
19,20,7,17,1977,11,DS,F,48.0,NaN
20,21,7,17,1977,14,DM,F,34.0,NaN
21,22,7,17,1977,15,NL,F,31.0,NaN
22,23,7,17,1977,13,DM,M,36.0,NaN
23,24,7,17,1977,13,SH,M,21.0,NaN
24,25,7,17,1977,9,DM,M,35.0,NaN
25,26,7,17,1977,15,DM,M,31.0,NaN
26,27,7,17,1977,15,DM,M,36.0,NaN
27,28,7,17,1977,11,DM,M,38.0,NaN
28,29,7,17,1977,11,PP,M,NaN,NaN
29,30,7,17,1977,10,DS,F,52.0,NaN
...,...,...,...,...,...,...,...,...,...
35519,35520,12,31,2002,9,SF,NaN,24.0,36.0
35520,35521,12,31,2002,9,DM,M,37.0,48.0
35521,35522,12,31,2002,9,DM,F,35.0,45.0
35522,35523,12,31,2002,9,DM,F,36.0,44.0
35523,35524,12,31,2002,9,PB,F,25.0,27.0
35524,35525,12,31,2002,9,OL,M,21.0,26.0
35525,35526,12,31,2002,8,OT,F,20.0,24.0
35526,35527,12,31,2002,13,DO,F,33.0,43.0
35527,35528,12,31,2002,13,US,NaN,NaN,NaN
35528,35529,12,31,2002,13,PB,F,25.0,25.0
35529,35530,12,31,2002,13,OT,F,20.0,NaN
35530,35531,12,31,2002,13,PB,F,27.0,NaN
35531,35532,12,31,2002,14,DM,F,34.0,43.0
35532,35533,12,31,2002,14,DM,F,36.0,48.0
35533,35534,12,31,2002,14,DM,M,37.0,56.0
35534,35535,12,31,2002,14,DM,M,37.0,53.0
35535,35536,12,31,2002,14,DM,F,35.0,42.0
35536,35537,12,31,2002,14,DM,F,36.0,46.0
35537,35538,12,31,2002,15,PB,F,26.0,31.0
35538,35539,12,31,2002,15,SF,M,26.0,68.0
35539,35540,12,31,2002,15,PB,F,26.0,23.0
35540,35541,12,31,2002,15,PB,F,24.0,31.0
35541,35542,12,31,2002,15,PB,F,26.0,29.0
35542,35543,12,31,2002,15,PB,F,27.0,34.0
35543,35544,12,31,2002,15,US,NaN,NaN,NaN
35544,35545,12,31,2002,15,AH,NaN,NaN,NaN
35545,35546,12,31,2002,15,AH,NaN,NaN,NaN
35546,35547,12,31,2002,10,RM,F,15.0,14.0
35547,35548,12,31,2002,7,DO,M,36.0,51.0
35548,35549,12,31,2002,5,NaN,NaN,NaN,NaN

In [7]:
surveys_df = pd.read_csv("surveys.csv")
surveys_df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN
5,6,7,16,1977,1,PF,M,14.0,NaN
6,7,7,16,1977,2,PE,F,NaN,NaN
7,8,7,16,1977,1,DM,M,37.0,NaN
8,9,7,16,1977,1,DM,F,34.0,NaN
9,10,7,16,1977,6,PF,F,20.0,NaN
10,11,7,16,1977,5,DS,F,53.0,NaN
11,12,7,16,1977,7,DM,M,38.0,NaN
12,13,7,16,1977,3,DM,M,35.0,NaN
13,14,7,16,1977,8,DM,NaN,NaN,NaN
14,15,7,16,1977,6,DM,F,36.0,NaN
15,16,7,16,1977,4,DM,F,36.0,NaN
16,17,7,16,1977,3,DS,F,48.0,NaN
17,18,7,16,1977,2,PP,M,22.0,NaN
18,19,7,16,1977,4,PF,NaN,NaN,NaN
19,20,7,17,1977,11,DS,F,48.0,NaN
20,21,7,17,1977,14,DM,F,34.0,NaN
21,22,7,17,1977,15,NL,F,31.0,NaN
22,23,7,17,1977,13,DM,M,36.0,NaN
23,24,7,17,1977,13,SH,M,21.0,NaN
24,25,7,17,1977,9,DM,M,35.0,NaN
25,26,7,17,1977,15,DM,M,31.0,NaN
26,27,7,17,1977,15,DM,M,36.0,NaN
27,28,7,17,1977,11,DM,M,38.0,NaN
28,29,7,17,1977,11,PP,M,NaN,NaN
29,30,7,17,1977,10,DS,F,52.0,NaN
...,...,...,...,...,...,...,...,...,...
35519,35520,12,31,2002,9,SF,NaN,24.0,36.0
35520,35521,12,31,2002,9,DM,M,37.0,48.0
35521,35522,12,31,2002,9,DM,F,35.0,45.0
35522,35523,12,31,2002,9,DM,F,36.0,44.0
35523,35524,12,31,2002,9,PB,F,25.0,27.0
35524,35525,12,31,2002,9,OL,M,21.0,26.0
35525,35526,12,31,2002,8,OT,F,20.0,24.0
35526,35527,12,31,2002,13,DO,F,33.0,43.0
35527,35528,12,31,2002,13,US,NaN,NaN,NaN
35528,35529,12,31,2002,13,PB,F,25.0,25.0
35529,35530,12,31,2002,13,OT,F,20.0,NaN
35530,35531,12,31,2002,13,PB,F,27.0,NaN
35531,35532,12,31,2002,14,DM,F,34.0,43.0
35532,35533,12,31,2002,14,DM,F,36.0,48.0
35533,35534,12,31,2002,14,DM,M,37.0,56.0
35534,35535,12,31,2002,14,DM,M,37.0,53.0
35535,35536,12,31,2002,14,DM,F,35.0,42.0
35536,35537,12,31,2002,14,DM,F,36.0,46.0
35537,35538,12,31,2002,15,PB,F,26.0,31.0
35538,35539,12,31,2002,15,SF,M,26.0,68.0
35539,35540,12,31,2002,15,PB,F,26.0,23.0
35540,35541,12,31,2002,15,PB,F,24.0,31.0
35541,35542,12,31,2002,15,PB,F,26.0,29.0
35542,35543,12,31,2002,15,PB,F,27.0,34.0
35543,35544,12,31,2002,15,US,NaN,NaN,NaN
35544,35545,12,31,2002,15,AH,NaN,NaN,NaN
35545,35546,12,31,2002,15,AH,NaN,NaN,NaN
35546,35547,12,31,2002,10,RM,F,15.0,14.0
35547,35548,12,31,2002,7,DO,M,36.0,51.0
35548,35549,12,31,2002,5,NaN,NaN,NaN,NaN

In [14]:
sub_year = surveys_df[(surveys_df.year == 1982)]
sub_year

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
5157,5158,1,1,1982,1,DO,F,37.0,49.0
5158,5159,1,1,1982,5,DM,F,34.0,42.0
5159,5160,1,1,1982,3,RM,F,16.0,11.0
5160,5161,1,1,1982,5,NL,F,33.0,193.0
5161,5162,1,1,1982,3,RM,F,17.0,10.0
5162,5163,1,1,1982,3,NL,F,34.0,163.0
5163,5164,1,1,1982,2,DS,F,49.0,78.0
5164,5165,1,1,1982,3,PF,M,15.0,6.0
5165,5166,1,1,1982,4,DM,M,36.0,49.0
5166,5167,1,1,1982,2,DM,M,35.0,45.0
5167,5168,1,1,1982,4,DS,M,52.0,117.0
5168,5169,1,1,1982,5,DM,F,35.0,49.0
5169,5170,1,1,1982,6,DS,F,49.0,124.0
5170,5171,1,1,1982,1,DS,M,52.0,168.0
5171,5172,1,1,1982,1,DS,M,53.0,160.0
5172,5173,1,1,1982,2,DS,M,50.0,83.0
5173,5174,1,1,1982,3,PM,M,20.0,24.0
5174,5175,1,1,1982,5,DM,M,36.0,40.0
5175,5176,1,1,1982,5,RM,M,16.0,9.0
5176,5177,1,1,1982,2,DO,F,37.0,61.0
5177,5178,1,1,1982,2,PE,F,20.0,25.0
5178,5179,1,1,1982,1,DO,F,37.0,38.0
5179,5180,1,1,1982,2,NL,M,NaN,206.0
5180,5181,1,1,1982,1,DM,M,37.0,51.0
5181,5182,1,1,1982,3,RM,F,16.0,15.0
5182,5183,1,1,1982,4,DM,F,36.0,51.0
5183,5184,1,1,1982,2,PE,F,19.0,21.0
5184,5185,1,1,1982,5,DM,M,38.0,56.0
5185,5186,1,1,1982,1,DM,M,35.0,42.0
5186,5187,1,1,1982,2,OL,F,21.0,27.0
...,...,...,...,...,...,...,...,...,...
7105,7106,11,22,1982,9,DS,F,50.0,132.0
7106,7107,11,22,1982,1,DO,M,36.0,50.0
7107,7108,11,22,1982,12,PF,F,16.0,7.0
7108,7109,11,22,1982,9,DS,M,49.0,130.0
7109,7110,11,22,1982,11,PF,M,16.0,6.0
7110,7111,11,22,1982,4,PF,M,15.0,6.0
7111,7112,11,22,1982,1,DO,F,34.0,49.0
7112,7113,11,22,1982,4,DS,F,52.0,119.0
7113,7114,11,22,1982,11,DS,F,51.0,111.0
7114,7115,11,22,1982,1,OL,M,19.0,26.0
7115,7116,11,22,1982,2,DO,F,35.0,45.0
7116,7117,11,22,1982,4,DM,F,33.0,45.0
7117,7118,11,22,1982,1,OL,M,21.0,39.0
7118,7119,11,22,1982,2,DO,F,36.0,43.0
7119,7120,11,22,1982,5,DM,M,37.0,46.0
7120,7121,11,22,1982,8,DS,F,50.0,106.0
7121,7122,11,22,1982,8,PF,M,15.0,6.0
7122,7123,11,22,1982,1,DM,F,33.0,35.0
7123,7124,11,22,1982,3,PF,M,15.0,6.0
7124,7125,11,22,1982,4,DS,F,48.0,122.0
7125,7126,11,22,1982,5,DM,M,35.0,41.0
7126,7127,11,22,1982,5,OL,M,22.0,43.0
7127,7128,11,22,1982,9,DM,F,33.0,36.0
7128,7129,11,22,1982,12,DS,F,48.0,102.0
7129,7130,11,22,1982,1,DM,M,37.0,48.0
7130,7131,11,22,1982,6,OT,F,19.0,27.0
7131,7132,11,22,1982,11,DM,M,36.0,45.0
7132,7133,11,22,1982,1,DM,F,34.0,35.0
7133,7134,11,22,1982,6,OT,M,21.0,24.0
7134,7135,11,22,1982,12,DM,M,37.0,41.0

In [15]:
group_df = sub_year[(sub_year.sex == M)]

NameError: name 'M' is not defined